version: '3.9'
services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_DEBUG=0
    volumes:
      - ${OLLAMA_MODELS_PATH}:/root/.ollama/models

  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - TOP_K=${TOP_K}
      - PROMPT_FILE=/app/${PROMPT_FILE}
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./data:/app/data
      - ./prompt.txt:/app/prompt.txt

  rag-test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rag-app
    command: pytest -v --tb=short
    environment:
      - TOP_K=${TOP_K}
      - PROMPT_FILE=/app/${PROMPT_FILE}
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./data:/app/data
      - ./prompt.txt:/app/${PROMPT_FILE}
